# Generated by Django 2.2.2 on 2019-06-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20190629_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.Category'),
        ),
    ]
