# Generated by Django 2.2.2 on 2019-06-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20190629_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgpath',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
