# Generated by Django 2.2.2 on 2019-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_category_imgpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('FACEBOOK', 'FACEBOOK'), ('EMAIL', 'EMAIL')], default='', max_length=10),
        ),
    ]
