# Generated by Django 2.2.3 on 2019-07-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_auto_20190702_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imgpath',
        ),
    ]
